#!/usr/bin/awk -f
BEGIN {
  N=split("one two three four five six seven eight nine 1 2 3 4 5 6 7 8 9",words)
}
{
  ls=-1
  rs=-1
  for (n = 1; n <= N; n++) {
    if (match($0, words[n] ".*$")) {
      if (ls == -1 || (RSTART < ls)) {
        ls = RSTART
        la = n < 10 ? n : words[n]
      }
    }
    if (match($0, "^.*" words[n])) {
      e = RLENGTH - length(words[n])
      if (rs == -1 || (e > rs)) {
        rs = e
        ra = n < 10 ? n : words[n]
      }
    }
  }
  n = la ra
  sum += n
}
END { print sum }
